### ISSUE TITLE
MultiView Commands

### ISSUE THREAD

**Issue by WuGGu** [haydendonald/blackmagic-atem-nodered#1]
Hi @haydendonald  thank you for your work.

I want to build with node-red an automation for our studio. and i want to change the sources in the multiview depending on the setting. One setting source 1 - 2 -3 in the first row. next setting source 4 -7 - 10 in the first row.
Would it be possible to add the multi view commands?

**Comment by haydendonald** [comment]
Hi @WuGGu thank you for your suggestion.
Yes this is possible, it's not supported directly at the moment but i'll add it when i have some spare time. In the meantime you can use the raw command functionality to send the commands out directly.

To do this you can send something like this:
```
var multiViewerId = 0; // Multiviewer 1-2 starting from 0
var windowIndex = 0; // Window index 1-10 starting from 0
var inputId = 1; 

var packet = new Buffer.from([multiViewerId, windowIndex, 0, 0]);
packet.writeUInt16BE(inputId, 3);
return {
    "payload": {
        "cmd": "raw",
        "data": {
            "name": "CMvI",
            "packet": packet
        }
    }
}
```
This should set multi viewer 1, window 1, to input 1. See https://www.skaarhoj.com/fileadmin/BMDPROTOCOL.html MultiViewer input for more.

(Note i haven't tested this so it might work)

**Comment by haydendonald** [comment]
Hi again @WuGGu i have updated to version 2.0.0 which adds multiViewerInput support which should hopefully help you out! I haven't been able to test it as i don't have access to an ATEM at the moment so please tell me if you find any issues!

**Comment by WuGGu** [comment]
Thank you for the quick response. I will test it tomorrow with a ATEM 2 M/E Switcher. =)
Thank you so much.
