### ISSUE TITLE
Feature Request - PiP On & Off - Atem Mini Pro

### ISSUE THREAD

**Issue by MDAR** [haydendonald/blackmagic-atem-nodered#10]
Hi

I didn't think I'd have a use for the PiP feature of this Atem Mini Pro, but it is possible to take an input from the Preview bus and push it to the PiP position, then continue to use the Preview bus as normal.

If it were possible to switch on and off the PiP on this Mini Pro I'd really appreciate it.

Assigning the PiP source should be easy enough, using your PreviewInput command.

Also being able to choose a position for the PiP would be amazing, however my feelings are that if an operator wanting to do that, they should be sat in front of the desk, or at least a Windows machine with Atem interface.

**Comment by haydendonald** [comment]
Hi
This functionality isn't listed in SKAARHOJ's research so i would have to reverse engineer the command structure.
So apologies but this won't happen for a bit as i don't have the time at the moment to reverse engineer it, if you want you can use a tool like Wireshark to try to find the commands that are sent and use the custom command feature.

Sorry again :)

**Comment by MDAR** [comment]
Okay, all understood.

Again, I'll try to sniff out the command.


*****

I'm amazed that such a prolific company doesn't embrace the community that are trying to increase the usability.

The project I'm working on is a classic example.

The client wants the very best, but deployed in the most simplistic way possible.

The select preview & AutoCut feature I've put together via a single toggle switch is working perfectly.

And for "manual" operation, I'm trying to create a one page webpage.

**Comment by haydendonald** [comment]
Yeah they are slowly opening up. They've released some documentation for their cameras which I've been working with lately but its very vague..

**Comment by MDAR** [comment]
Hi

I've had a strange email from BlackMagic regarding working with "third parties", which basically said... "No, we don't."
Then went on to blar blar blar about exposing the IP and prividing too much access to their software.

I' considering a reply along the lines of..

"Had it not been for the great work done to get Node-RED working with this fabulous desk, I would have been forced to buy a Roland desk...."

"How much damage does that do to your revenue?" (If I'm not the only one who walks away from the brand)

However, suffice to say that the cleint is delighted with the functionality and the fact that the whole system is 80% automated (100% for most occasions) is an absolute delight.

Thank you so much for all your efforts, if there is anythng I can help you with, please just ask.

And just to round off, I have go around the PiP and Keyers control issues by recording macros in the desk.
I can't show a state for the keyers in the UI, but I can switch them on and off, so that's good enough for now.

**Comment by haydendonald** [comment]
Thats good to hear, im glad to hear that! 👍 
As for the third party issue it doesn't effect me as i don't make any revenue from the project it solely exists because we needed to automate our buildings and there wasn't a solution available that was flexible enough to provide what we needed.

**Comment by MDAR** [comment]
> it solely exists because we needed to automate our buildings and there wasn't a solution available that was flexible enough to provide what we needed.

Yeah, isn't that the case with most development.

So what kind of use case do you have for the BlackMagic Design hardware?

When you say you want to automate your biuldings, what are you doing within a building that requires an automated pro vision mix setup?

I could share the link to the YouTube channel to see the output from the project I worked on, but as always, what is outputted doesn't always reflect the amount of technology in the background.

Best wishes,

Stuart
