### ISSUE TITLE
How do I request that macro property information be received?

### ISSUE THREAD

**Issue by ke5stl** [haydendonald/blackmagic-atem-nodered#12]
Thank you for making this module!

I want to retrieve from the ATEM switcher, the list of macros that are configured, on demand from node-red side.

How is that done?

I see that sometimes, the ATEM node is receiving this information, but, how do I trigger it to be sent from the ATEM at-will?

I'd like to be able to send the ATEM a command, the result of which is that the ATEM sends to node-red the set of data.

eg: so that when a macro gets added/removed, I can query/trigger the ATEM with a command, and end up with the current set of macro names & IDs.

**Comment by haydendonald** [comment]
Hi sorry for the late response i seem to have missed the notification..

You should be able to request this information using
```
return {
    "payload": {
        "cmd": "macroProperties",
        "data": {}
    }
}
```
This will give you an array with the properties of each macro :)
