### ISSUE TITLE
How to start/stop recording? - ATEM Mini PRO ISO 

### ISSUE THREAD

**Issue by mattyg-repo** [haydendonald/blackmagic-atem-nodered#13]
Hey 
i'm trying to have control over the Recording inside the ATEM 
I tried it with raw commands, but didn't get it to work.

- Start / Stop Recording
- get Status of Recording
- set File Name for Recording
- set TimeCode for Recording 

maybe someone has already made it?

**Comment by haydendonald** [comment]
Hi!
Sorry for the late response and also sorry but this is not supported. You might be able to have a look at https://github.com/nrkno/tv-automation-atem-connection there is a recording feature, maybe you might be able to use this and pass the raw command?
