### ISSUE TITLE
"Camera ID is missing";

### ISSUE THREAD

**Issue by kltv21** [haydendonald/blackmagic-atem-nodered#17]
msg = { "payload": {
        "cmd": "cameraControl",
        "data": {
                "camera": 1,
                "iris": 0,
                "focus": 0,
                "overallGain": "6db",
                "whiteBalance": 3600,
                "zoomSpeed": 0,
                "lift": {
                    "red": 0.0,
                    "green": 0.0,
                    "blue": 0.0,
                    "yellow": 0.0
                },
                "gamma": {
                    "red": 0.0,
                    "green": 0.0,
                    "blue": 0.0,
                    "yellow": 0.0
                },
                "gain": {
                    "red": 0.0,
                    "green": 0.0,
                    "blue": 0.0,
                    "yellow": 0.0
                },
                "lumMix": 0,
                "hue": 50,
                "shutter": "1/75",
                "contrast": 50,
                "saturation": 0,
                "zoomPosition": 0
              }
           }
        }

**Comment by haydendonald** [comment]
Hi @kltv21 sorry for the late response. The camera id can be seen in msg.payload.data.camera above (1).

Thanks :)
