### ISSUE TITLE
Using it NodeJS only

### ISSUE THREAD

**Issue by Toshiba01** [haydendonald/blackmagic-atem-nodered#18]
Hi, 

would it be possible to use your script with nodejs cli directly without using the Node-Red interface? If yes, can you point me into that direction, please? I love your hard work! Share with me a "buy me a coffee" link if you've got one ;)

**Comment by haydendonald** [comment]
Hi @Toshiba01 sorry for the late response.. No, it's not possible sadly, i wish i did develop it that way originally. There is the [atem-connection](https://www.npmjs.com/package/atem-connection) project that might help you out though, i've been using it for some of my other projects! :)

And no, i don't have a buy me a coffee link never thought about it..

Thanks!
