### ISSUE TITLE
audioMixerMonitor and audioMixerInput return no data - Atem Mini

### ISSUE THREAD

**Issue by saccojt** [haydendonald/blackmagic-atem-nodered#19]
Firstly, thank you for all of your work on this blackmagic-atem-nodered!

I am using this node with the Atem Mini Extreme ISO and the audioMixerMonitor and audioMixerInput will not return any data. I suspect that these use Fairlight which could possibly be retrieved through raw command using work done by nrkno - https://github.com/nrkno/sofie-atem-connection/tree/master/src/commands/Fairlight
I am relatively new to javascript and node.js... 

Could you give me an example of sending a raw get command? this would be a huge help!

**Comment by haydendonald** [comment]
Hi @saccojt,
I'm sorry that this feature isn't available for you.

The raw command might help you.. 

Firstly do you get anything out of the node by attaching a debug node to it? Could you post the output here?
If you do it would have a raw command and data sent which would be in one of the files in the sofie-atem-connection project.

**Comment by saccojt** [comment]
This is all that is coming through for audioMixerInput and audioMixerMonitor when initial data is sent.

1/20/2023, 8:27:31 AMnode: msg payload
initial : msg.payload : Object
object
cmd: "audioMixerInput"
data: object
empty

1/20/2023, 8:27:31 AMnode: msg payload
initial : msg.payload : Object
object
cmd: "audioMixerMonitor"
data: object
empty

I am trying to read the audio levels in real time so I can run automations based on an db level threshold.

Thanks for your help!

**Comment by haydendonald** [comment]
What happens if you change the level of a audio channel?

Also can you copy the output by clicking this button please :)
![image](https://user-images.githubusercontent.com/12867415/213828398-363c7e85-fc0a-49e9-8d77-aea8e2d29906.png)
Results to:
```
{"_msgid":"851266f7f294ea83","payload":1674260360824,"topic":""}
```

Thanks!

**Comment by saccojt** [comment]
Nothing changes with the audio level. I figured out that the atem mini uses Fairlight instead of the legacy audio mixer. 

Also, I was able to send a raw command:
`// This enables or disables receiving the 10Hz audio level update packets
var msg = {
    "payload": {
        "cmd": "raw",
        "data": {
            "name": "SFLN",
            "packet": Buffer.from([1, 0, 0, 0])
        }
    }
};

return msg;` 

Now I just need to parse the data and figure out some conversions. I have been using [https://docs.openswitcher.org/](url) to find some of this info but I am still struggling with converting the output array to understandable info.

Here is what I am getting after enabling audio level updates:
`{"raw":{"flag":"sync","length":48,"name":"FMLv","packet":[0,48,0,0,70,77,76,118,255,255,255,255,255,255,1,0,0,5,216,240,216,240,216,240,216,240,0,0,0,0,0,0,216,240,216,240,216,240,216,240,216,240,216,240,216,240,216,240]},"data":{},"cmd":"raw"}`

Thank you so much for your continued help!

**Comment by haydendonald** [comment]
Hmm.. I had a little google for the FMLv command and couldn't really find anything..
Your best bet would be to find if someone has already documented the FLMv command.. Orr the super fun way would be to figure it out yourself.

The packet itself if i remember is the entire packet sent by the atem including "FMLv" from 4 to 8 above.
So your data would be from 9 to end.

![image](https://user-images.githubusercontent.com/12867415/213839642-6c149576-ab4a-410f-9cee-bb0ae40bfa35.png)

Hopefully someone has already figured it out for you!!!!
