### ISSUE TITLE
Node crashing on redeploy

### ISSUE THREAD

**Issue by domfie** [haydendonald/blackmagic-atem-nodered#2]
Hi,

first thing: Your atem node is truly awesome!
Saved me a LOT of headache 👍 

But with the current state I'm craching node on every redeploy.
The Problem seems to come from the messageCallbacks:

Every line of 
`for(var i in messageCallbacks) {`
throws a undefined error for messageCallbacks.

I think the close function does not enough cleanup.
The reference to messageCallbacks breaks on redeployment, maybe just the reference to the object itself is missing.

I will have a deeper look on this issue at the end of the week if you don't get ahead of me :)

**Comment by haydendonald** [comment]
Hi thank you for the support, glad to help!

Hmm I’ve seen this error before but I haven’t seen it for a long time. Is this happening on every redeploy or randomly? I’ll have a look at this shortly :)

**Comment by haydendonald** [comment]
Hi again,
I'm looking at the issue and i think i have already fixed this issue cause i cannot find any line of code with for(var i in messageCallbacks). Can you please tell me what version you are running and maybe try updating. The latest version is 2.0.0 .

Thanks!

**Comment by domfie** [comment]
Thank you for your quick reply.

For example here: https://github.com/haydendonald/blackmagic-atem-nodered/blob/master/commands/previewInput.js#L33

I've set sendStatusUpdates and sendInitialData to yes. I will try to update my ATEM and debug the problem tomorrow :)

**Comment by haydendonald** [comment]
Oh awesome thanks for finding it! I’ll fix that as soon as I can :)

**Comment by haydendonald** [comment]
Hi i have fixed the bug, please let me know how it goes! (Version 2.1.0)

**Comment by domfie** [comment]
Thanks, that did the trick, Atem running stable now 👍
