### ISSUE TITLE
Missing setParameter.focus

### ISSUE THREAD

**Issue by edouard-durand-imagination** [haydendonald/blackmagic-atem-nodered#21]
Hi,

Base on this file:
https://github.com/haydendonald/blackmagic-atem-nodered/blob/26f4f7a374389abd6a83df9a5821cba7c517bc96/commands/cameraControl.js#L217

This is missing its buffer.

**Comment by haydendonald** [comment]
Sorry I'm not sure if I understand. What is the problem physically?

**Comment by edouard-durand-imagination** [comment]
As you can see, your code is calling commandList.cameraOptions.setParameter.focus, but this value is missing its buffer value.

You can check it here: https://github.com/haydendonald/blackmagic-atem-nodered/blob/26f4f7a374389abd6a83df9a5821cba7c517bc96/commands/commandList.js#L113

**Comment by haydendonald** [comment]
Oh. I see. Sorry about that.
I am not at a computer at the moment, if i forget to fix it please reply again 😊

**Comment by edouard-durand-imagination** [comment]
Thank you!
Sure thing, I am trying to find the right value of it but not sure about it.

```
focus: new Buffer([0x80, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00]),
```

**Comment by edouard-durand-imagination** [comment]
I have rum some test it does affect the focus but not really stable (it feels the focus is a bit random); could you have a look when you have a chance?

Thank you

**Comment by haydendonald** [comment]
I don't have access to a camera anymore. Can you try setting values from 0-x and see if there is a range of values that work / don't.

It is sending a 16bit value but it's possible that it might be incorrect.
