### ISSUE TITLE
Undefined messageCallbacks are back

### ISSUE THREAD

**Issue by domfie** [haydendonald/blackmagic-atem-nodered#4]
Hi,

today I observed the same bug as before your fix. After a restart of nodered it was gone. Looking through the code after work got me thinking about the context of the network node may not get cleared (https://discourse.nodered.org/t/node-context-does-not-reset-on-redeploy/14733/9). 
It seems that the commands are getting resetted but the connectionState stays connected. This results in processData getting called without the previous call of initializeData, which sets the messageCallbacks.
I will try to dump the value of connectionState and if the function closeConnection is triggered next time this bug happens. (quick fix could be to assign an empty array to the messageCallbacks, may resulting in messages from the atem not being processed when this bug occurs)
It could also happen that on partial redeployment only the Atem Node gets redeployed, but the network node stays the same resulting in the callbacks of the Atem Node getting lost.

Sorry for beeing so hypothetically but I currently do not have enough time to debug this bug in-depth due to a tight project deadline :/

**Comment by haydendonald** [comment]
Hi Domfile,
Sorry i didn't get an email for this one :O so sorry for the late response..
Is this the same issue that was occurring in the previewInput file? Do you have a specific file/line where the error is occurring? 

No problem! I have the same issue plus the added fun that some of the older code i was still learning and didn't know of certain issues :(

I'll have a look to see if i can find any instances of the pesky messageCallbacks error again :)

**Comment by domfie** [comment]
Hey Hayden :)
I just received a new ATEM Mini Pro (Beast of a product 👍 ) and its functions can be controlled just like a normal Atem.
I think this Problem resulted from my bad setup having two configuration nodes laying around :/ Everything works fine now :)

**Comment by haydendonald** [comment]
Awesome! Yeah the ATEM Mini is a pretty cool product :)
