### ISSUE TITLE
Set and get transition problem

### ISSUE THREAD

**Issue by studiofarela** [haydendonald/blackmagic-atem-nodered#5]
I'm using the SET and GET transition commands on nodeRed, I have a nodered crash.
You can see the attachments I don't understand where this may come from. even when the Atem Switcher sends Perform CUT, Perform Auto, and Transition Position. I use the atem switcher version 8.2.1.

Thank you for your help.

<img width="1123" alt="Capture d’écran 2020-05-11 à 17 59 56" src="https://user-images.githubusercontent.com/65180959/81583166-3b345000-93b1-11ea-978b-8dc479809870.png">

**Comment by haydendonald** [comment]
Hi @studiofarela thank you for letting me know about this! I have fixed the issue in version 2.1.1 :)
