### ISSUE TITLE
Atem not connecting - reports "Atem is Full"

### ISSUE THREAD

**Issue by MDAR** [haydendonald/blackmagic-atem-nodered#8]
Hi

This probably isn't strictly a Node-RED > Atem issue, as I'm struggling to get the Windows 10 software to connect either.
(But the Atem Setup software is connecting on the same LAN / USB)

I've only had the Atem Mini Pro for 48 hours and I've managed to achieve 80% of what I had hoped for with Node-RED.

This morning everything was working well, then suddenly the Atem node refused to connect, reporting that "The Atem was full"

Have you any idea as to what this means? and importantly what I can do to reset it and prevent it from happening again?

What I have done to try to repair it...

I powered up the Atem Mini Pro while holding down the "MIC1 ON" button, which seems to put it into boot-loader mode and allows Atem Setup to detect it and flash a replacement firmware.

This didn't resolve anything with Node-RED, I would a live connection for about 10 seconds, then it would drop. (5 Minutes later, it was back to reporting the Atem was full)

The Windows 10 software connected 3 times, then went back to refusing to even see the Mini Pro via USB or LAN.

(While the Atem Setup software could see it from the same machine and the same LAN)

I'm writing the firmware again, but I'm not convinced the outcome will be any different.

Right now, I'll hunt down the Atem support and see what they say.. Which based on the poor response from previous questions, I'm not holding out much hope.

(I wish I had known this was the case, I would have gone with the Roland V1-HD that I found first)

**Comment by haydendonald** [comment]
Hi
Sorry to hear you're having these issues with your ATEM Min Pro.

How many clients do you have connected to the ATEM? There is a limit on the amount of clients that can be connected, which i'm not sure what that limit is with Mini Pro, but i'd assume it would be at least 2.

Did you have the issue only connecting the unit without NodeRed? I have found in my development that our ATEM if sent data it does not expect would close its network till rebooted.

Hopefully you'll find a resolution with BMD support.

**Comment by MDAR** [comment]
Thanks for your comments, that really helps me to find the "fault"

> but i'd assume it would be at least 2.
> 
> Did you have the issue only connecting the unit without NodeRed? I have found in my development that our ATEM if sent data it does not expect would close its network till rebooted.

That's curious.

I rebooted a number of times, with different combinations of connections.
Sadly the results were the same each time.

It simply refused to connect. (With or without Node-RED running (dead as opposed to simply disabling the Flow)

The only thing that seems to have done the trick is to completely re-write the firmware, by holding down

"MIC1 ON" & "Black" while applying power.

It's up and running again after another firmware write.

However, this time, I have ONLY tried to connect with Node-RED.

Next step is to work out why the ESP8266 GPio pin decides to invert for no reason. (I suspect I need a larger Resistor)

**Comment by MDAR** [comment]
FYI

BMD are closed on a Saturday...

"because Nobody needs tech support on a weekend, there simply isn't anyone using their hardware outside of office hours..."
