### ISSUE TITLE
Feature Request - Load Still image into Media Player / Still- Atem Mini Pro

### ISSUE THREAD

**Issue by MDAR** [haydendonald/blackmagic-atem-nodered#9]
I don't even know if this is possible, but I have to assume that something might be because of how the Windows 10 software is operating and the lack of media storage on the Mini

Is it possible to add the ability to load an image in the Still media source of the Atem Mini Pro, while retaining the Alpha channel?

(I'm happy to let you have remote access to the Mini Pro here to have a play around)

Many thanks

Stuart

**Comment by haydendonald** [comment]
Hi
Sorry again but this feature hasn't been reverse engineered yet, and i'm not even sure how to tackle this if i'm honest.

**Comment by MDAR** [comment]
Thanks.

I understand.


I'll see what I can discover with wireshark (the next thing to learn how to use).

I'll try to discover the following :-

* How to change the current Still from the media pool (Mini Pro supports 20 still images)

* What format images are transferred in & what the command is. (If we're really lucky, it'll be something like Base64)
